### ISSUE TITLE
editorial help on the training docs

### ISSUE THREAD

**Issue by brianleroux** [smallwins/learn.begin.com#1]
pls ensure this stuff actually works, makes sense and conforms to our style guide (one or more PRs is cool)

- [x] https://github.com/smallwins/training.begin.com/blob/master/src/md/index.md
- [x] https://github.com/smallwins/training.begin.com/blob/master/src/md/basic/foundations/setup.md
- [x] https://github.com/smallwins/training.begin.com/blob/master/src/md/basic/foundations/hello-world.md
- [x] https://github.com/smallwins/training.begin.com/blob/master/src/md/basic/foundations/deployment.md

**Comment by kmanion** [comment]
I've completed & Brian has merged edit passes on all of these pages. Next I will tackle the frontend patterns section.
