### ISSUE TITLE
Handling state/Tracking sessions example project dev environment doesn't start.

### ISSUE THREAD

**Issue by ShawnHosea** [smallwins/learn.begin.com#24]
**Expected behavior**
Handling state/Tracking sessions example project dev environment doesn't start. ARC project should start up in development mode/sandbox mode after typing `npm start` in terminal.

**Description of bug**
`npm start` should start the sandbox but instead throws errors.

**Steps to reproduce**
Follow these instructions carefully: https://learn.begin.com/basic/state/sessions
On step 9 it says to paste the sandbox script inside of `package.json`. I believe it should have been created on step 2 after typing `arc init` in the terminal but was never created.

**Screenshots**
<img width="691" alt="Screen Shot 2020-02-19 at 1 21 00 AM" src="https://user-images.githubusercontent.com/36789673/74807318-24042b80-52b6-11ea-9026-8bbf7062951e.png">
<img width="1679" alt="Screen Shot 2020-02-19 at 1 32 07 AM" src="https://user-images.githubusercontent.com/36789673/74808149-31221a00-52b8-11ea-936e-c1701015e1e6.png">

**Desktop**
 - OS: [e.g. macOS]
 - Browser: [e.g. Chrome, Firefox]
 - Version: [e.g. 22.4.201]

**Mobile**
 - Device: [e.g. iPhone 6]
 - OS: [e.g. iOS 8.1]
 - Browser [e.g. Chrome, Safari]
 - Version [e.g. 8.14.590]

**Additional context or notes**
Add any other context or notes about the problem here.

**Comment by brianleroux** [comment]
missing .arc file!

**Comment by brianleroux** [comment]
or! possibly because you didn't run `npm start`

**Comment by pchinjr** [comment]
I realized what happened, another user saw the same thing. I have created (#26) to solve this issue.
