### ISSUE TITLE
Are we using 'API Gateway' in this example? [src/md/basic/backend/graphql.md (Line: 12)]

### ISSUE THREAD

**Issue by jagadeeshpalaniappan** [smallwins/learn.begin.com#44]
**Description of document issue**

I am slightly confused, Are we using AWS **'API Gateway'** in this below example ?

learn.begin.com/src/md/basic/backend/graphql.md (Line: 12)
```
In this guide we will implement a GraphQL API using AWS Lambda, API Gateway and DynamoDB from scratch.
```
Could you please provide more info?

**Comment by brianleroux** [comment]
hey sorry! just noticed this issue =( this is using API Gateway yes!
